### ISSUE TITLE
Request: Update windows binary

### ISSUE THREAD

**Issue by lars18th** [slhck/ffmpeg-debug-qp#14]
Hi,

First: thank you all for the last improvement!
However, one suggestion: please update the binary precompiled version for Windows.

Regards.

**Comment by slhck** [comment]
I don't have Windows in order to do that, unfortunately.
Maybe if @plebreton has the time – he has been so kind to do that for the previous versions.

**Comment by plebreton** [comment]
In principle, it is quite easy to apply the last patch and make a new build of the windows file (I have already done that). 

But so far, I did not resolved the bug which was mentioned there: 
https://github.com/slhck/ffmpeg-debug-qp/issues/8
So I am not sure if it makes too much sense. 

For the other bug, I am not sure. There is a parameter to control the number of threads used for the decoding. I am not sure if that it is not taken into account with the pre-build libav libraries that I am using or if it something else. Maybe I should start with rebuilding all these libraries. So far, I haven't find the time to dig too much into this. 

I did not see the bug at first as it was not there on very short videos (like the test.mp4 in the repository). But with longer videos, it is definitely there. Currently, I am mostly using Mac computers, so it hasn't been on the top of my list. I made that build, as I thought it could be useful for windows users, but not really.. sorry. 

I will try to find some time to rebuild the libav libraries and see if I can improve this.

**Comment by slhck** [comment]
I think you should not spend too much time on it. You have already helped a lot in the past. But the whole project is built around a hack, in fact, and Windows was never a priority. In principle we could just supply a Docker image and let people use that, which would be more portable.

**Comment by lars18th** [comment]
Sorry @slhck ,

A Docker image compared to a Windows binary is a huge difference. Please, don't discard the Windows support. If you can't fix the bug #8, then go forward. But even this, please share a Windows binary.

Thank you for this useful tool.
Regards.

**Comment by plebreton** [comment]
I made a PR with the updated binary. 

@slhck Thanks :)

**Comment by lars18th** [comment]
Thank you @plebreton !

Waiting for the merge.

**Comment by lars18th** [comment]
Hi @plebreton ,

After the commit/merge from the PR #17 done by @slhck at https://github.com/slhck/ffmpeg-debug-qp/issues/12#issuecomment-597485248 , I suggest to recompile the Windows binary and update it.

Please... :wink:

**Comment by slhck** [comment]
I know I am repeating myself, but I think this is a significant bottleneck and we should either automatically build the Windows binary (e.g. using appveyor) or drop support for it. I will look into whether appveyor will do the job.

**Comment by slhck** [comment]
Please test whether this binary works for you:

https://ci.appveyor.com/api/projects/slhck/ffmpeg-debug-qp/artifacts/build.zip

**Comment by lars18th** [comment]
> Please test whether this binary works for you:
> 
> https://ci.appveyor.com/api/projects/slhck/ffmpeg-debug-qp/artifacts/build.zip

Hi @slhck ,

Yes, it works! However, I don't see any difference with the current binary.

**Comment by lars18th** [comment]
Hi @slhck ,

Well done! https://github.com/slhck/ffmpeg-debug-qp/pull/18
I hope it will be merge asap.

Regards.

**Comment by slhck** [comment]
Were you expecting a difference between the build artifact and the current binary? I thought that was exactly the purpose.

**Comment by lars18th** [comment]
OK. Then we need to wait one or two days to check the auto-compilation of the Windows binary.

Thank you @slhck !

**Comment by lars18th** [comment]
Hi @slhck ,

Please, re-upload the libraries ZIP to the repository. After the merge of the PR #18 only the appveyor autobuild is available. It contains the binary (plus another non-useful files). But the _libraries_ (*.dll files, like `avcodec-58.dll`, `avformat-58.dll`, etc.) are *unavailable*. And without them the binary don't work.

Regards.

**Comment by slhck** [comment]
It's at this point where my experience with building Windows software is lacking. I thought that building the `.sln` file would put all required files under `build`, which is then packaged by Appveyor.

Can you suggest changes to the Appveyor config so that the DLLs are included, too? https://github.com/slhck/ffmpeg-debug-qp/blob/master/appveyor.yml

Or do they have to be manually uploaded? (Since they're just basic ffmpeg DLLs, I think we can also just put them into the build folder as-is.)

**Comment by plebreton** [comment]
I have no experience with appveyor, but I think you can just put the dll in the build folder as you say.
In the sln file, I could have post build rules to copy the dlls, but I didn't since it would be about putting the dll somewhere else and then copy them in the folder. No real point of doing that, they can just be already there :)

**Comment by slhck** [comment]
Okay, I see. I added a ZIP containing the DLL files and made a short note in the README.

**Comment by lars18th** [comment]
> Okay, I see. I added a ZIP containing the DLL files and made a short note in the README.

Great! Then I feel this issue can be closed. You agree?
