### ISSUE TITLE
Request: Multiple output formats

### ISSUE THREAD

**Issue by lars18th** [slhck/ffmpeg-debug-qp#25]
Hi,

I suggest to add the option to write _two_ fileformats at time. For example, ldjson _and_ csv. Then we don't need two passes to complete the ldjson + cvs file.

You agree?

**Comment by slhck** [comment]
As much as I can see the use for that, I would rather not make this tool a "Swiss army knife" that includes every possible feature. I maintain a lot of packages that work similarly and only have an either/or kind of output mechanism. It is very much dependent on how the user will parse the data, which is not a concern of this tool. Also I've rarely seen users with a need for two file formats with the same data. 

If you output to JSON or CSV there are good tools or Python packages that can convert between either of the two the formats.
