### ISSUE TITLE
Can we determine the video quality by simply verifying the average IQP frame's QP?

### ISSUE THREAD

**Issue by liweijian** [slhck/ffmpeg-debug-qp#32]
Hi @slhck ,

It's very usefully to find this git repo, and ffmpeg-debug-qp is really amazing.

I have a simple question on determining the video quality, let me know if I was wrong.

I just curious if maybe we could determine the video quality is not so good by the following rules:

1. The average value of I frame's QP is larger than the whole video's average QP.
2. The average value of P frame's QP is smaller than I frame's.

I just wanna figure out if there's any simple way to detect the not so good encode videos from a list of candidate files.

If it reasonable, I might kick off a PR to this repo ASAP. Since the output of `-a` and `-m` contains too much info that I might not need. I believe that we could add another option to calculate the average/ranges of QPs of I/B/P.

**Comment by slhck** [comment]
I would recommend to use a proper bitstream based quality model such as this one: https://github.com/Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3

**Comment by liweijian** [comment]
Thanks for your guide, I just found the paper [Bitstream-Based Model Standard for 4K/UHD: ITU-T P.1204.3](https://ieeexplore.ieee.org/document/9123110)  mentioned from your reply.

From the title, it seems that we could only use it to verify the 4K/UHD videos, but after reading the abstract:

> We outline the databases on which the model was trained and validated as part of the competition, and perform an additional evaluation using a total of four independently created databases, where resolutions varied from 360p to 2160p, and frame rates from 15–60fps, using realistic coding and bitrate settings

It seems that this model also work for the traditional videos with low resolutions, am I right?

**Comment by slhck** [comment]
That is correct. It goes up to UHD/4K but you can measure the quality of any other video with lower resolution. The 4K part assumes that the video is shown on 4K screens, but if you are comparing quality in relative terms, this will have no effect on the rank order.
