### ISSUE TITLE
Binary File For Linux for ffmpeg-debug-qp

### ISSUE THREAD

**Issue by Dionne97** [slhck/ffmpeg-debug-qp#33]
May you kindly assist me with the binary for linux. I used Pip install and it gives me the following error

Could not find executable at /usr/local/bin/ffmpeg_debug_qp

**Comment by slhck** [comment]
I just realized that the README file was a bit unclear. Under Linux you have to first build the binary.

- Download or clone this Git repository
- Install the requirements per the instructions
- Run `make` to build the binary

Then, a file `ffmpeg_debug_qp` will be created.

Now you can copy this to an executable path on your system:

```
sudo cp ./ffmpeg_debug_qp /usr/local/bin/
```

Finally, when you run the Python tool, it should be able to find the `ffmpeg_debug_qp` binary that you just built.

**Comment by slhck** [comment]
I updated the README to make this process clearer. If you have any questions, please simply ask.
