### ISSUE TITLE
Request: Support for HEVC and VP9

### ISSUE THREAD

**Issue by JoshuaEbenezer** [slhck/ffmpeg-debug-qp#34]
Hi,
Thanks for this great tool. Hope you can add support for HEVC and VP9. Are you aware of any open-source tools that already do this for HEVC and VP9?

**Comment by slhck** [comment]
For this repo we depend on what ffmpeg is doing, however you can check out https://github.com/Telecommunication-Telemedia-Assessment/bitstream_mode3_videoparser for a different bitstream parser that handles H.264, HEVC and VP9.
