### ISSUE TITLE
HEVC support

### ISSUE THREAD

**Issue by HahaOptimus** [slhck/ffmpeg-debug-qp#35]
hi, I'm trying to use this tool to extract HEVC video frame qp value but failed, now H265 is popular enough in many tasks, so when could you update this tool to support HEVC files？

**Comment by slhck** [comment]
This program is simply a wrapper around ffmpeg that sets a particular flag, which in turn makes ffmpeg output more debug info:

https://github.com/slhck/ffmpeg-debug-qp/blob/2a95e9aa53a64e4bea33cc8a1391de587759ba2a/ffmpeg_debug_qp.c#L220-L223

If this is not implemented for HEVC, then the actual ffmpeg source code needs to be updated to support this. I cannot do much here, sorry!
