### ISSUE TITLE
Macroblocks Metadata : types, segmentation, interlaced

### ISSUE THREAD

**Issue by TomMunSan** [slhck/ffmpeg-debug-qp#37]
Hello everyone,

First of all thanks for the project!! It has simplified my workflow!!.

I am interested in understand the macroblocks matadata such us, mb type,segmentation interlaced. 

Regardless of reading the [doxygen](https://ffmpeg.org/doxygen/3.0/group__lavu__log__constants.html#ga030300ea4843c53b2fe178a434964b39) or the [ffmpeg documentation](http://ffmpeg.org/ffmpeg.html#toc-Generic-options) I have not found a clue of understanding the specific nomenclature used for the mb metadata.

According to json created with `ffmpeg_debug_qp` and the ` ffmpeg loglevel - debug` results. 
Is obvious that "i" and "I" are for mb intra prediction although, what is the difference between them upper and lower case?
For the rest of types I must guess ... 

1. For mb `*type*` : 
  - "i" and "I" , intra prediction 
  - "d" and "D" , direct mode
  - "<" and ">", inter 
  - "X" , skip

On the other hand, *segmetation* and *interlaced* fields are allways empty. (like with test.mp4).

I sincerely apreaciate your help for this issue.

Best,

**Comment by slhck** [comment]
Looking at `mpegutils.c` in FFmpeg 4.4, you can see:

```c
// Type & MV direction
if (IS_PCM(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "P");
else if (IS_INTRA(mb_type) && IS_ACPRED(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "A");
else if (IS_INTRA4x4(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "i");
else if (IS_INTRA16x16(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "I");
else if (IS_DIRECT(mb_type) && IS_SKIP(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "d");
else if (IS_DIRECT(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "D");
else if (IS_GMC(mb_type) && IS_SKIP(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "g");
else if (IS_GMC(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "G");
else if (IS_SKIP(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "S");
else if (!USES_LIST(mb_type, 1))
    av_log(avctx, AV_LOG_DEBUG, ">");
else if (!USES_LIST(mb_type, 0))
    av_log(avctx, AV_LOG_DEBUG, "<");
else {
    av_assert2(USES_LIST(mb_type, 0) && USES_LIST(mb_type, 1));
    av_log(avctx, AV_LOG_DEBUG, "X");
}

// segmentation
if (IS_8X8(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "+");
else if (IS_16X8(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "-");
else if (IS_8X16(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "|");
else if (IS_INTRA(mb_type) || IS_16X16(mb_type))
    av_log(avctx, AV_LOG_DEBUG, " ");
else
    av_log(avctx, AV_LOG_DEBUG, "?");


if (IS_INTERLACED(mb_type))
    av_log(avctx, AV_LOG_DEBUG, "=");
else
    av_log(avctx, AV_LOG_DEBUG, " ");
```

**Comment by slhck** [comment]
As for segmentation and interlaced, I have not seen them in practice anymore.

**Comment by TomMunSan** [comment]
Thank you Werner!!

**Comment by slhck** [comment]
You're welcome, good luck with your research!
