### ISSUE TITLE
ffmpeg v4 and mac m1 compile error

### ISSUE THREAD

**Issue by F4RAN** [slhck/ffmpeg-debug-qp#38]
i cant build this package in mac m1 and gets many errors:
ffmpeg-debug-qp-master make
Package libavdevice was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavdevice.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavdevice' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libswresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswresample.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswresample' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavdevice was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavdevice.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavdevice' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libswresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswresample.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswresample' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
cc   ffmpeg_debug_qp.o    -o ffmpeg_debug_qp
Undefined symbols for architecture arm64:
  "_av_dict_set", referenced from:
      _open_codec_context in ffmpeg_debug_qp.o
  "_av_find_best_stream", referenced from:
      _open_codec_context in ffmpeg_debug_qp.o
  "_av_frame_alloc", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_frame_free", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_frame_get_pkt_size", referenced from:
      _decode_packet in ffmpeg_debug_qp.o
  "_av_frame_unref", referenced from:
      _decode_packet in ffmpeg_debug_qp.o
  "_av_free", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_free_packet", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_get_media_type_string", referenced from:
      _open_codec_context in ffmpeg_debug_qp.o
  "_av_get_picture_type_char", referenced from:
      _decode_packet in ffmpeg_debug_qp.o
  "_av_get_pix_fmt_name", referenced from:
      _decode_packet in ffmpeg_debug_qp.o
  "_av_image_alloc", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_init_packet", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_log", referenced from:
      _decode_packet in ffmpeg_debug_qp.o
  "_av_log_default_callback", referenced from:
      _log_callback in ffmpeg_debug_qp.o
  "_av_log_set_callback", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_log_set_level", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_read_frame", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_register_all", referenced from:
      _main in ffmpeg_debug_qp.o
  "_av_strerror", referenced from:
      _av_make_error_string in ffmpeg_debug_qp.o
  "_avcodec_alloc_context3", referenced from:
      _open_codec_context in ffmpeg_debug_qp.o
  "_avcodec_close", referenced from:
      _main in ffmpeg_debug_qp.o
  "_avcodec_decode_video2", referenced from:
      _decode_packet in ffmpeg_debug_qp.o
  "_avcodec_find_decoder", referenced from:
      _open_codec_context in ffmpeg_debug_qp.o
  "_avcodec_open2", referenced from:
      _open_codec_context in ffmpeg_debug_qp.o
  "_avcodec_parameters_to_context", referenced from:
      _open_codec_context in ffmpeg_debug_qp.o
  "_avformat_close_input", referenced from:
      _main in ffmpeg_debug_qp.o
  "_avformat_find_stream_info", referenced from:
      _main in ffmpeg_debug_qp.o
  "_avformat_open_input", referenced from:
      _main in ffmpeg_debug_qp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffmpeg_debug_qp] Error 1

**Comment by slhck** [comment]
You're unfortunately not giving me enough information to understand what the exact problem is. How did you install ffmpeg exactly?

I should note that Homebrew now ships 5.x so the README is no longer valid.

I'm considering archiving this project in general, since it's deprecated for a while now.

**Comment by F4RAN** [comment]
Hello, thanks for your response
i installed ffmpeg@4 from homebrew
![image](https://user-images.githubusercontent.com/25338592/218545956-40d14ef5-6485-4953-bc19-6a33fdbe629e.png)
but when I tried to compile I got the above error
you can see in below picture:
![image](https://user-images.githubusercontent.com/25338592/218546349-08a302f8-a8e5-42f5-b8cd-b9715d36fab8.png)
Regards,

**Comment by slhck** [comment]
Try setting

    export PKG_CONFIG_PATH="/opt/homebrew/opt/ffmpeg@4/lib/pkgconfig

Before running make.

**Comment by F4RAN** [comment]
Problem solved thanks a lot
