### ISSUE TITLE
Feature Request: Library version

### ISSUE THREAD

**Issue by ndtreviv** [slhck/ffmpeg-debug-qp#6]
I would love this as a reusable, thread-safe library that I could write JNI wrappers for (and obviously contribute back - maybe python ones as well).

What are the chances?

**Comment by slhck** [comment]
I'm not sure that is possible. This entire project is a bit of a hack; it relies on [setting an internal debug flat](https://github.com/slhck/ffmpeg-debug-qp/blob/master/ffmpeg_debug_qp.c#L183) and capturing hardcoded output created by the ffmpeg H.264 decoder via STDERR.

A more reasonable path forward would be to add a feature to ffmpeg that exports the decoded QP values in a sane format (or stores them internally) upon setting a particular debug flag. Then this could be used in other projects, or, via an API.
