### ISSUE TITLE
Request: Read from STDIN

### ISSUE THREAD

**Issue by lars18th** [slhck/ffmpeg-debug-qp#9]
Hi,

It will be very useful if we can use the `stdin` pipe as input, like: `ffmpeg [...] -f mpegts pipe:1 | ffmpeg-debug-qp - 2> qp-values.txt`

I hope you want to implement it.
Thank you!

**Comment by slhck** [comment]
This would require some rewriting to open pipes instead of files, which I do not have the time to implement. You are welcome to provide a PR to add this functionality.

**Comment by lars18th** [comment]
Hi @slhck ,

My last PR #22 implements this functionality. Please review and merge it!

Regards.

**Comment by lars18th** [comment]
I close this issue as the functionality is now implemented.
